export const CONFIG = {
    // Physics
    GRAVITY: 1.5,
    GROUND_FRICTION: 0.05,
    AIR_FRICTION: 0.01,
    FIXED_DT: 1000 / 60,

    // Fighter defaults
    PLAYER_HP: 100,
    ENEMY_BASE_HP: 60,
    MOVE_SPEED: 5,
    JUMP_FORCE: -12,
    DASH_SPEED: 10,
    DASH_DURATION: 8,
    DASH_COOLDOWN: 30,
    DASH_IFRAMES: [2, 5],

    // Combat
    COMBO_BUFFER_WINDOW: 600,
    COMBO_BUFFER_SIZE: 8,
    COMBO_CHAIN_WINDOW: 12,
    BLOCK_DAMAGE_REDUCTION: 0.8,
    AIR_BLOCK_REDUCTION: 0.5,
    BLOCK_KB_REDUCTION: 0.2,
    BLOCK_STRUCTURAL_NEGATION: 1.0,
    HITSTUN_BASE: 10,
    HIT_CANCEL_WINDOW: 4,
    WHIFF_RECOVERY_PENALTY: 1.2,

    // Combo scaling
    COMBO_SCALE: [1.0, 0.9, 0.8, 0.7, 0.6, 0.5],
    STRUCTURAL_SCALES_WITH_COMBO: false,

    // Wall mechanics
    WALL_SLIDE_SPEED_MULT: 0.3,
    WALL_SLIDE_MAX_DURATION: 120,
    WALL_JUMP_FORCE: 14,
    WALL_JUMP_VECTOR: { x: 0.7, y: -0.7 },
    WALL_JUMP_GRACE: 6,
    WALL_JUMP_CHAIN_DECAY: 0.85,
    WALL_JUMP_MAX_CHAIN: 5,
    WALL_SLIDE_ENTRY_WINDOW: 10,

    // Movement
    AIR_CONTROL: 0.6,
    FAST_FALL_AIR_CONTROL: 0.4,
    AIR_ATTACK_DRIFT: 0.2,
    FLOAT_GRAVITY_MULT: 0.3,
    FAST_FALL_GRAVITY_MULT: 2.5,
    JUMP_BUFFER: 6,
    COYOTE_TIME: 6,

    // NEAT
    NEAT_POPULATION_SIZE: 40,
    NEAT_ELITISM: 0.15,
    NEAT_MUTATION_RATE: 0.3,
    NEAT_CROSSOVER_RATE: 0.5,
    DEAD_POOL_THRESHOLD: 6,
    SENSOR_COUNT_BASE: 20,
    OUTPUT_COUNT_BASE: 8,
    STRUCTURAL_SENSOR_COUNT: 8,

    // Waves
    KILLS_TO_ADVANCE_BASE: 8,
    KILLS_SCALE_PER_WAVE: 2,
    HP_SCALE_PER_WAVE: 0.1,
    DAMAGE_SCALE_PER_WAVE: 0.05,
    SPEED_SCALE_PER_WAVE: 0.02,
    BOSS_EVERY_N_WAVES: 5,
    BOSS_HP_MULT: 3.0,
    BOSS_MUTATION_COUNT: 2,
    BOSS_BONE_THICKNESS: 2.0,
    BOSS_INTRO_FRAMES: 120,        // 2s dramatic pause before boss
    BOSS_DEFEAT_HEAL: 30,          // HP restored on boss kill
    WAVE_TRANSITION_FRAMES: 90,    // 1.5s pause between waves

    // Rendering
    CANVAS_WIDTH: 960,
    CANVAS_HEIGHT: 540,
    DEBUG_HITBOXES: false,
    DEBUG_HURTBOXES: false,
    DEBUG_STRUCTURAL: false,
    CAMERA_LERP: 0.1,

    // Arena
    ARENA_WIDTH: 960,
    ARENA_HEIGHT: 540,
    WALL_THICKNESS: 40,
    PLATFORM_WIDTH: 200,
    PLATFORM_HEIGHT: 12,
    PLATFORM_Y: 320,
    GROUND_Y: 520,

    // Player structural bonuses
    PLAYER_BONE_HP_MULT: 1.5,
    PLAYER_JOINT_HP_MULT: 1.5,
    PLAYER_STRUCTURAL_HEAL_ON_BOSS: true,

    // Skeleton
    BONE_LINE_WIDTH: 3,
    HEAD_RADIUS: 8,
    JOINT_RADIUS: 2,

    // Particles
    PARTICLE_MAX_POOL: 300,
    PARTICLE_HIT_SPARK_COUNT: 8,
    PARTICLE_HIT_SPARK_LIFE: 300,
    SHOW_DAMAGE_NUMBERS: true,

    // Audio
    MASTER_VOLUME: 1.0,
    EFFECTS_VOLUME: 0.8,

    // Pause
    PAUSE_OVERLAY_ALPHA: 0.5,
};
